// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreningIRazvoj.Infrastruktura.Podaci;

#nullable disable

namespace TreningIRazvoj.Infrastruktura.Migracije
{
    [DbContext(typeof(TreningIRazvojKontekst))]
    [Migration("20260701141314_PocetnaMigracija")]
    partial class PocetnaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.KategorijaPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("KategorijePrograma");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Predavac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imejl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Interni")
                        .HasColumnType("bit");

                    b.Property<string>("OblastStrucnosti")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Imejl")
                        .IsUnique();

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Prijava", b =>
                {
                    b.Property<int>("ZaposleniId")
                        .HasColumnType("int");

                    b.Property<int>("RazvojniProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("BrojPoena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OcenaPrograma")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProcenatPrisustva")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ZaposleniId", "RazvojniProgramId");

                    b.HasIndex("RazvojniProgramId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.RazvojniProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaProgramaId")
                        .HasColumnType("int");

                    b.Property<int?>("MinimalanBrojPoena")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Objavljen")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeUSatima")
                        .HasColumnType("int");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaProgramaId");

                    b.HasIndex("PredavacId");

                    b.ToTable("RazvojniProgrami");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Zaposleni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imejl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Odeljenje")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RadnoMesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Imejl")
                        .IsUnique();

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Prijava", b =>
                {
                    b.HasOne("TreningIRazvoj.Domen.Modeli.RazvojniProgram", "RazvojniProgram")
                        .WithMany("Prijave")
                        .HasForeignKey("RazvojniProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreningIRazvoj.Domen.Modeli.Zaposleni", "Zaposleni")
                        .WithMany("Prijave")
                        .HasForeignKey("ZaposleniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RazvojniProgram");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.RazvojniProgram", b =>
                {
                    b.HasOne("TreningIRazvoj.Domen.Modeli.KategorijaPrograma", "KategorijaPrograma")
                        .WithMany("RazvojniProgrami")
                        .HasForeignKey("KategorijaProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreningIRazvoj.Domen.Modeli.Predavac", "Predavac")
                        .WithMany("RazvojniProgrami")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KategorijaPrograma");

                    b.Navigation("Predavac");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.KategorijaPrograma", b =>
                {
                    b.Navigation("RazvojniProgrami");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Predavac", b =>
                {
                    b.Navigation("RazvojniProgrami");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.RazvojniProgram", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("TreningIRazvoj.Domen.Modeli.Zaposleni", b =>
                {
                    b.Navigation("Prijave");
                });
#pragma warning restore 612, 618
        }
    }
}
