@TreningIRazvoj.API_HostAddress = https://localhost:7133
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNmMwOTFkMy1kM2VhLTRkYmMtYmY2My0xNjg5MGQxYTcwZTgiLCJlbWFpbCI6ImFkbWluQGZpcm1hLnJzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiNmMwOTFkMy1kM2VhLTRkYmMtYmY2My0xNjg5MGQxYTcwZTgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZmlybWEucnMiLCJpbWUiOiJBbGVrc2FuZGFyIiwicHJlemltZSI6IlN0b2ppbGtvdmnEhyIsImp0aSI6ImFiNzFlYmYyLWQ3M2QtNDNlNy1hOTc3LTRkMGE2OTkwMWNjNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJleHAiOjE3ODI5NjQ2MzEsImlzcyI6IlRyZW5pbmdJUmF6dm9qLkFQSSIsImF1ZCI6IlRyZW5pbmdJUmF6dm9qLktsaWplbnQifQ.fwUfwr6UgMz7V1OhCBWJ29vobKB6DAcYuWNC0jtvGy4

### Prijavljivanje administratora

POST https://localhost:7133/api/autentifikacija/prijava
Content-Type: application/json

{
  "imejl": "admin@firma.rs",
  "lozinka": "Admin123!"
}